
model_name : "swin_s_upper"
checkpoint_interval : 1
keep_checkpoints : 1
num_classes : 4
in_channels : 3
num_epochs : 5000
backend: "cv2"
image_size : !!python/tuple [512, 512]
val_interval : 1
resume : None
work_dir : "swinunetblitze"
load_from : Null
batch_size : 2
pretrained : True
persistent_workers : False
num_workers : 0
classes : !!python/tuple ["0", "1", "2", "3"]
dataroot : "C:/HSA/HSA-Data/projects/49398886-fba3-41cf-b016-dcfd8ac6654e/dataset/"

train_img_prefix:
  img_path: train/images
  seg_map_path: train/labels

val_img_prefix:
  img_path: valid/images
  seg_map_path: valid/labels

test_img_prefix:
  img_path: valid/images
  seg_map_path: valid/labels
