
model_name : "swin_s_upper"
checkpoint_interval : 1
keep_checkpoints : 1
num_classes : 6 #CHANGE THIS 
in_channels : 3
num_epochs : 5000
backend: "cv2"
image_size : !!python/tuple [1024, 1024] #CHANGE THIS
val_interval : 1
resume : None
work_dir : "melanieswinsupper"
load_from : "https://download.openmmlab.com/mmsegmentation/v0.5/mask2former/mask2former_swin-t_8xb2-90k_cityscapes-512x1024/mask2former_swin-t_8xb2-90k_cityscapes-512x1024_20221127_144501-36c59341.pth"
batch_size : 2
pretrained : True
persistent_workers : False
num_workers : 0
classes : !!python/tuple ["0", "1", "2", "3", "4", "5"] #CHANGE THIS
dataroot : "C:/Users/philmarq/Documents/JB/Datasets/Datasets_New/Segmentation/big/Gesund_Adenom_Karzinom/Default_512px/"
dataroot: "C:/Users/philmarq/Downloads/dataset (1)/dataset/"
train_img_prefix:
  img_path: train/images
  seg_map_path: train/labels

val_img_prefix:
  img_path: valid/images
  seg_map_path: valid/labels

test_img_prefix:
  img_path: valid/images
  seg_map_path: valid/labels
