
model_name : "dino_r50"
checkpoint_interval : 1
keep_checkpoints : 1
num_classes : 2
in_channels : 2
num_epochs : 100
image_size : !!python/tuple [512, 512]
val_interval : 1
backend: "tifffile"
resume : None
work_dir : "C:/Users/philmarq/Desktop/custom_model_training/fl_test"
load_from : "https://download.openmmlab.com/mmdetection/v3.0/dino/dino-4scale_r50_8xb2-12e_coco/dino-4scale_r50_8xb2-12e_coco_20221202_182705-55b2bba2.pth"
batch_size : 1
pretrained : False
persistent_workers : False
num_workers : 0
classes : !!python/tuple ["CD8+ Cells"]
dataroot : "C:/Users/philmarq/Downloads/fl_datasets/fl_datasets/dataset_od_2ch_512"
train_ann_file : "train.json"
train_img_prefix:
  img: images/

val_ann_file : "valid.json"
val_img_prefix:
  img: images/

test_ann_file : "valid.json"
test_img_prefix:
  img: images/