
model_name : "dino_r50"
checkpoint_interval : 1
keep_checkpoints : 1
num_classes : 1
in_channels : 3
num_epochs : 50
image_size : !!python/tuple [1024, 1024]
val_interval : 1
resume : None
work_dir : "firstapitest"
load_from : "https://download.openmmlab.com/mmdetection/v3.0/dino/dino-4scale_r50_8xb2-12e_coco/dino-4scale_r50_8xb2-12e_coco_20221202_182705-55b2bba2.pth"
batch_size : 1
pretained : False
persistent_workers : False
num_workers : 0
classes : !!python/tuple ["0"]
dataroot : "C:/Users/philmarq/Downloads/dataset/"
train_ann_file : "annotations/instances_train2017.json"
train_img_prefix:
  img: train2017/
  seg: annotations/panoptic_train2017/

val_ann_file : "annotations/instances_train2017.json"
val_img_prefix:
  img: train2017/
  seg: annotations/panoptic_val2017/

test_ann_file : "annotations/instances_train2017.json"
test_img_prefix:
  img: train2017/
  seg: annotations/panoptic_val2017/