
model_name : "mask2former_swin_t"
checkpoint_interval : 1
keep_checkpoints : 1
num_classes : 4
in_channels : 3
backend: "cv2"
num_epochs : 150
image_size : !!python/tuple [768, 768]
val_interval : 1
resume : None
work_dir : "alltogether_512_trainedon768"
load_from : "C:/Users/philmarq/Downloads/mask2former_swin-s-p4-w7-224_8xb2-lsj-50e_coco_20220504_001756-c9d0c4f2.pth"
batch_size : 1
pretrained : True
persistent_workers : False
num_workers : 0
classes : !!python/tuple ["0", "1", "2", "3"]
dataroot : "C:/HSA/HSA-Data/projects/074219d0-4345-4896-a335-288f9c7a92ba/dataset/"
train_ann_file : "annotations/instances_train2017.json"
train_img_prefix:
  img: train2017/
  seg: annotations/panoptic_train2017/

val_ann_file : "annotations/instances_val2017.json"
val_img_prefix:
  img: val2017/
  seg: annotations/panoptic_val2017/

test_ann_file : "annotations/instances_val2017.json"
test_img_prefix:
  img: val2017/
  seg: annotations/panoptic_val2017/